language: cpp

compiler:
  - gcc
  - clang
  
script: 
  - cd build
  - cmake ..
  - make

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcfitsio3 libcfitsio3-dev
  - sudo apt-get install -qq libccfits0 libccfits-dev
  - sudo apt-get install -qq opencl-headers fglrx 
  - sudo apt-get install -qq libboost-thread-dev libboost-system-dev
